#pragma once

typedef unsigned DOBOT_STATUS;

const unsigned UINT_BIT = 32;

/*
@brief: define the result mask
@author: JoMar
@note: up to 3 bits
@date: 2016-06-12
*/

const unsigned DOBOT_RESULT_SHIFT		= (UINT_BIT - 4);
const unsigned DOBOT_ERROR_MASK			= (0x00000000 << DOBOT_RESULT_SHIFT);
const unsigned DOBOT_SUCCESS_MASK		= (0x00000001 << DOBOT_RESULT_SHIFT);
const unsigned DOBOT_WARN_MASK			= (0x00000002 << DOBOT_RESULT_SHIFT);
const unsigned DOBOT_CHECK_RESULT_MASK	= (0xffffffff << DOBOT_RESULT_SHIFT);

//default value
const unsigned DOBOT_OK = 0;


/*
@brief: define the subsystem mask
@author: JoMar
@note: up to 5 bits
@date: 2016-06-12
*/

const unsigned DOBOT_SUBSYS_SHIFT		= (DOBOT_RESULT_SHIFT - 5);
const unsigned COORDINATE_SUBSYS_MASK	= (0x00000000 << DOBOT_SUBSYS_SHIFT);
const unsigned PALLET_SUBSYS_MASK		= (0x00000001 << DOBOT_SUBSYS_SHIFT);

/*
@brief: define the coordinate subsystem error status
@author: JoMar
@date: 2016-06-12
*/

const unsigned DOBOT_ERR_COORD_MASK							= (DOBOT_ERROR_MASK | COORDINATE_SUBSYS_MASK);
const unsigned DOBOT_ERR_COORD_SET_MULTI_BASE				= ((DOBOT_STATUS)(DOBOT_ERR_COORD_MASK + 0));
const unsigned DOBOT_ERR_COORD_DEL_ID_NONEXISTENT			= ((DOBOT_STATUS)(DOBOT_ERR_COORD_MASK + 1));
const unsigned DOBOT_ERR_COORD_CONVERT_ORIGIN_NONEXISTENT	= ((DOBOT_STATUS)(DOBOT_ERR_COORD_MASK + 2));
const unsigned DOBOT_ERR_COORD_CONVERT_TARGET_NONEXISTENT	= ((DOBOT_STATUS)(DOBOT_ERR_COORD_MASK + 3));
const unsigned DOBOT_ERR_COORD_ERGODIC_EMPTY				= ((DOBOT_STATUS)(DOBOT_ERR_COORD_MASK + 4));
const unsigned DOBOT_ERR_COORD_GET_ID_NOTE					= ((DOBOT_STATUS)(DOBOT_ERR_COORD_MASK + 5));
const unsigned DOBOT_ERR_COORD_GET_ID						= ((DOBOT_STATUS)(DOBOT_ERR_COORD_MASK + 6));

/*
@brief: define the coordinate subsystem success status
@author: JoMar
@date: 2016-06-12
*/

const unsigned DOBOT_SUC_COORD_MASK			= (DOBOT_SUCCESS_MASK | COORDINATE_SUBSYS_MASK);
const unsigned DOBOT_SUC_COORD_CREATE		= ((DOBOT_STATUS)(DOBOT_SUC_COORD_MASK + 0));
const unsigned DOBOT_SUC_COORD_MODIFY		= ((DOBOT_STATUS)(DOBOT_SUC_COORD_MASK + 1));
const unsigned DOBOT_SUC_COORD_DEL			= ((DOBOT_STATUS)(DOBOT_SUC_COORD_MASK + 2));
const unsigned DOBOT_SUC_COORD_CONVERT		= ((DOBOT_STATUS)(DOBOT_SUC_COORD_MASK + 3));
const unsigned DOBOT_SUC_COORD_ERGODIC		= ((DOBOT_STATUS)(DOBOT_SUC_COORD_MASK + 4));
const unsigned DOBOT_SUC_COORD_GET_ID_NOTE	= ((DOBOT_STATUS)(DOBOT_SUC_COORD_MASK + 5));
const unsigned DOBOT_SUC_COORD_GET_ID		= ((DOBOT_STATUS)(DOBOT_SUC_COORD_MASK + 6));


/*
@brief: define the coordinate subsystem warn status
@author: JoMar
@date: 2016-06-12
*/

const unsigned DOBOT_WAR_COORD_MASK			= (DOBOT_WARN_MASK | COORDINATE_SUBSYS_MASK);
const unsigned DOBOT_WAR_COORD_CONVERT_SAME = ((DOBOT_STATUS)(DOBOT_WAR_COORD_MASK + 0));
const unsigned DOBOT_WAR_COORD_ERGODIC_END	= ((DOBOT_STATUS)(DOBOT_WAR_COORD_MASK + 1));


/*
@brief: define the pallet subsystem error status
@author: JoMar
@date: 2016-06-12
*/

const unsigned DOBOT_ERR_PALLET_MASK							= (DOBOT_ERROR_MASK | PALLET_SUBSYS_MASK);
const unsigned DOBOT_ERR_PALLET_SET_NONLENGHT					= ((DOBOT_STATUS)(DOBOT_ERR_PALLET_MASK + 0));
const unsigned DOBOT_ERR_PALLET_SET_ZONE_LESS					= ((DOBOT_STATUS)(DOBOT_ERR_PALLET_MASK + 1));
const unsigned DOBOT_ERR_PALLET_SET_CREATE_COORD				= ((DOBOT_STATUS)(DOBOT_ERR_PALLET_MASK + 2));
const unsigned DOBOT_ERR_PALLET_SET_ORIGIN_NONEXISTENT			= ((DOBOT_STATUS)(DOBOT_ERR_PALLET_MASK + 3));
const unsigned DOBOT_ERR_PALLET_DEL_NONEXISTENT					= ((DOBOT_STATUS)(DOBOT_ERR_PALLET_MASK + 4));
const unsigned DOBOT_ERR_PALLET_GETCELL_PALLET_NONEXISTENT		= ((DOBOT_STATUS)(DOBOT_ERR_PALLET_MASK + 5));
const unsigned DOBOT_ERR_PALLET_GETCELL_ZONE_OVER				= ((DOBOT_STATUS)(DOBOT_ERR_PALLET_MASK + 6));
const unsigned DOBOT_ERR_PALLET_GETCELL_CONVERT					= ((DOBOT_STATUS)(DOBOT_ERR_PALLET_MASK + 7));
const unsigned DOBOT_ERR_PALLET_GETPALLET_NONEXISTENT			= ((DOBOT_STATUS)(DOBOT_ERR_PALLET_MASK + 8));
const unsigned DOBOT_ERR_PALLET_GETPALLETID_NONEXISTENT			= ((DOBOT_STATUS)(DOBOT_ERR_PALLET_MASK + 9));
const unsigned DOBOT_ERR_PALLET_GETPALLETID_BYINDEX_NONEXISTENT = ((DOBOT_STATUS)(DOBOT_ERR_PALLET_MASK + 10));
const unsigned DOBOT_ERR_PALLET_ERGODIC_EMPTY					= ((DOBOT_STATUS)(DOBOT_ERR_PALLET_MASK + 11));



/*
@brief: define the pallet subsystem success status
@author: JoMar
@date: 2016-06-12
*/

const unsigned DOBOT_SUC_PALLET_MASK				= (DOBOT_SUCCESS_MASK | PALLET_SUBSYS_MASK);
const unsigned DOBOT_SUC_PALLET_MODIFY				= ((DOBOT_STATUS)(DOBOT_SUC_PALLET_MASK + 0));
const unsigned DOBOT_SUC_PALLET_CREATE				= ((DOBOT_STATUS)(DOBOT_SUC_PALLET_MASK + 1));
const unsigned DOBOT_SUC_PALLET_DEL					= ((DOBOT_STATUS)(DOBOT_SUC_PALLET_MASK + 2));
const unsigned DOBOT_SUC_PALLET_GETCELL				= ((DOBOT_STATUS)(DOBOT_SUC_PALLET_MASK + 3));
const unsigned DOBOT_SUC_PALLET_GETPALLET			= ((DOBOT_STATUS)(DOBOT_SUC_PALLET_MASK + 4));
const unsigned DOBOT_SUC_PALLET_GETPALLETID			= ((DOBOT_STATUS)(DOBOT_SUC_PALLET_MASK + 5));
const unsigned DOBOT_SUC_PALLET_GETPALLET_BYINDEX	= ((DOBOT_STATUS)(DOBOT_SUC_PALLET_MASK + 6));
const unsigned DOBOT_SUC_PALLET_ERGODIC				= ((DOBOT_STATUS)(DOBOT_SUC_PALLET_MASK + 7));

/*
@brief: define the pallet subsystem warn status
@author: JoMar
@date: 2016-06-12
*/

const unsigned DOBOT_WAR_PALLET_MASK		= (DOBOT_WARN_MASK | PALLET_SUBSYS_MASK);
const unsigned DOBOT_WAR_PALLET_ERGODIC_END = ((DOBOT_STATUS)(DOBOT_WAR_PALLET_MASK + 0));
